CREATE DATABASE loginregistro;

SET NAMES 'utf8';

USE loginregistro;


DROP TABLE IF EXISTS usuarios;
CREATE TABLE usuarios (
  id INT(11) NOT NULL AUTO_INCREMENT,
  usuario VARCHAR(255) BINARY DEFAULT NULL,
  pass VARCHAR(255) BINARY DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_bin;